#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker20260107"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "a79314ae858b46d0a92ab9fe1f8bb1fd" }
]

[assets]
directory = "./public"
